var credits = {
    text: [
    "  Made by: Avreen Kaur",
    "  Naruto : Game - Naruto: Ninja Council (The Spriters Resource)",
    "  Background and Scenery: Anokolisa (Twitter: @anokolisa)",
    "  Toxic Frogs (Enemy Entity) : Eduardo Scarpato (Twitter: @eduscarpato)",
    "  TCSS 491, Winter 2024 - Chris Marriot",
    ]
}

var level1 = {
    players:   [{x: 0, y: 0}],

    ground:   [{ x: 0, y: 4, size: 15 }, 
               { x: 15, y: 10, size: 15 },
               { x: 44, y: 7, size: 15 },
               ],

    dirt:     [{ x: 0, y: 5, size: 6, type: "Plain"},
               { x: 4, y: 6, size: 5, type: "Plain"},
               { x: 14, y: 5, size: 1, type: "Plain"},
               { x: 13, y: 6, size: 2, type: "Plain"},
               { x: 5, y: 7, size: 10, type: "Mid"},
               { x: 44, y: 8, size: 15, type: "Plain"},
               { x: 44, y: 9, size: 15, type: "Mid"},
               { x: 15, y: 11, size: 15, type: "Plain"},
               { x: 15, y: 12, size: 15, type: "Mid"},
               ],
    
    bricks:   [{ x: 6, y: 5, size: 8 }, 
               { x: 7, y: 6, size: 6 }, 
               ],
    
    edges:     [{ x: 15, y: 4, type: "RightTop"},
                { x: 15, y: 5, type: "RightMid"},
                { x: 15, y: 6, type: "RightMid"},
                { x: 15, y: 7, type: "RightBot"},
                { x: 14, y: 10, type: "LeftTop"},
                { x: 30, y: 10, type: "RightTop"},
                { x: 43, y: 7, type: "LeftTop"},
                { x: 43, y: 8, type: "LeftMid"},
                { x: 43, y: 9, type: "LeftBot"},
                { x: 59, y: 7, type: "RightTop"},
                { x: 59, y: 8, type: "RightMid"},
                { x: 59, y: 9, type: "RightBot"},
                { x: 14, y: 10, type: "LeftTop"},
                { x: 14, y: 11, type: "LeftMid"},
                { x: 14, y: 12, type: "LeftBot"},
                { x: 30, y: 10, type: "RightTop"},
                { x: 30, y: 11, type: "RightMid"},
                { x: 30, y: 12, type: "RightBot"},
                ],

    platforms: [{ x: 12,   y: 10.5,  size: 1, scale: 1, type: "Double", moving: true, direction: -1, speed: 200 },
                { x:  7.5, y: 10,    size: 1, scale: 1, type: "Double", moving: true, direction:  1, speed: 100 }, 
                { x:  5.5, y: 10.5,  size: 1, scale: 1, type: "Double", moving: true, direction: -1, speed: 100 },
                { x:  1,   y: 7.40,  size: 1, scale: 1, type: "Single", moving: true, direction:  1, speed: 50},
                { x: 17,   y: 5.5,   size: 1, scale: 2, type: "Double", moving: false, direction: 1, speed: 0},
                { x: 20,   y: 7,     size: 1, scale: 2, type: "Double", moving: false, direction: 1, speed: 0},
                { x: 23,   y: 8.5,   size: 1, scale: 2, type: "Double", moving: false, direction: 1, speed: 0},
                { x: 32,   y: 10.25, size: 1, scale: 1, type: "Single", moving: true, direction: 1, speed: 75},
                { x: 36,   y: 9,     size: 1, scale: 2, type: "Double", moving: false, direction: 1, speed: 0},
                { x: 41,   y: 8,     size: 1, scale: 1, type: "Single", moving: true, direction: -1, speed: 100},
                { x: 3 ,   y: 9,     size: 1, scale: 1, type: "Single", moving: true, direction: -1, speed: 150},
                ],
 
    beams:     [{ x: 17.90, y: 5.75,   size: 2.25, scale: 2, type: "Long" }, 
                { x: 20.90, y: 7,  size: 1.5, scale: 2, type: "Long" }, 
                { x: 23.90, y: 8.5, size: 0.5, scale: 2, type: "Long" }, 
                { x: 36.90, y: 9, size: 10, scale: 2, type: "Long" }, 
                ],

    trunks:   [{ x: 6, y: 0, size: 2 },
               { x: 6, y: 1, size: 2 },
               { x: 6, y: 2, size: 2 },
               { x: 6, y: 3, size: 2 },
               { x: 55, y: 0, size: 2 },
               { x: 55, y: 1, size: 2 },
               { x: 55, y: 2, size: 2 },
               { x: 55, y: 3, size: 2 },
               { x: 55, y: 4, size: 2 },
               { x: 55, y: 5, size: 2 },
               { x: 55, y: 6, size: 2 },
               { x: 1.5, y: 9, size: 3 },
               { x: 1.5, y: 10, size: 3 },
               { x: 1.5, y: 11, size: 3 },
               { x: 1.5, y: 12, size: 3 },
               { x: 1.5, y: 13, size: 3 },
               { x: 1.5, y: 14, size: 3 },
               { x: 1.5, y: 15, size: 3 },
               { x: 1.5, y: 16, size: 3 },
                ],

    branches: [{ x: 7.75, y: 2, size: 2 },
               { x: 56.75, y: 4.75, size: 2 },
              ],

    leaves:   [{ x: 4.5, y: -2.5, size: 4, color: "Orange"},
               { x: 2.5, y: -4,   size: 5, color: "Orange"},
               { x: 2,   y: 5.9,  size: 4, color: "Purple"},
               { x: 6,   y: -4,   size: 5, color: "Orange"},
               { x: 0,   y: 5.5,  size: 5, color: "OrangeBrown"},
               { x: -3,  y: 4.5,  size: 5, color: "Purple"},
               { x: 55,  y: -1,   size: 5, color: "Purple"},
               { x: 53,  y: -2,   size: 5, color: "Purple"},
               { x: 52,  y: -1,   size: 5, color: "Purple"},
               { x: 53,  y: -2,   size: 5, color: "Purple"},
               ],

    frogs:    [{ x: 10, y: 0, scale: 3, color: "blue_blue" },
               { x: 25, y: 0, scale: 2, color: "green_brown" },
               { x: 28, y: 0, scale: 5, color: "purple_white" },
               { x: 50, y: 0, scale: 3, color: "purple_white" },
               { x: 55, y: 0, scale: 3, color: "blue_blue" },
               { x: 45, y: 0, scale: 3, color: "green_brown" },
               ],

    cats:     [
                { x: 57, y: 0, scale: 5, chosenOne: true}
              ],
               
    pills:     [{ x: 1.35, y: 6.95, scale: 4},
                { x: 9, y: 0, scale: 4},
                ],
};

var level2 = {
    players: [
    { x: 0, y: 0 },
    ],
    ground: [
    { x: 0, y: 4, size: 1 },
    { x: 1, y: 4, size: 1 },
    { x: 2, y: 4, size: 1 },
    { x: 3, y: 4, size: 1 },
    { x: 4, y: 4, size: 1 },
    { x: 5, y: 4, size: 1 },
    { x: 6, y: 4, size: 1 },
    { x: 6, y: 29, size: 1 },
    { x: 7, y: 4, size: 1 },
    { x: 8, y: 4, size: 1 },
    { x: 9, y: 4, size: 1 },
    { x: 10, y: 4, size: 1 },
    { x: 11, y: 4, size: 1 },
    { x: 12, y: 4, size: 1 },
    { x: 13, y: 4, size: 1 },
    { x: 14, y: 4, size: 1 },
    { x: 15, y: 4, size: 1 },
    { x: 21, y: 6, size: 1 },
    { x: 22, y: 6, size: 1 },
    { x: 23, y: 6, size: 1 },
    { x: 33, y: 8, size: 1 },
    { x: 34, y: 8, size: 1 },
    { x: 35, y: 8, size: 1 },
    { x: 36, y: 8, size: 1 },
    { x: 37, y: 8, size: 1 },
    { x: 38, y: 8, size: 1 },
    { x: 39, y: 8, size: 1 },
    { x: 40, y: 8, size: 1 },
    { x: 41, y: 8, size: 1 },
    ],
    dirt: [
    { x: 0, y: 5, size: 1, type: "Plain" },
    { x: 0, y: 6, size: 1, type: "Plain" },
    { x: 0, y: 7, size: 1, type: "Plain" },
    { x: 0, y: 10, size: 1, type: "Mid" },
    { x: 1, y: 5, size: 1, type: "Plain" },
    { x: 1, y: 6, size: 1, type: "Plain" },
    { x: 1, y: 7, size: 1, type: "Plain" },
    { x: 1, y: 10, size: 1, type: "Mid" },
    { x: 2, y: 6, size: 1, type: "Plain" },
    { x: 2, y: 7, size: 1, type: "Plain" },
    { x: 2, y: 8, size: 1, type: "Plain" },
    { x: 2, y: 9, size: 1, type: "Plain" },
    { x: 2, y: 10, size: 1, type: "Mid" },
    { x: 3, y: 7, size: 1, type: "Plain" },
    { x: 3, y: 8, size: 1, type: "Plain" },
    { x: 3, y: 9, size: 1, type: "Plain" },
    { x: 3, y: 10, size: 1, type: "Mid" },
    { x: 4, y: 7, size: 1, type: "Plain" },
    { x: 4, y: 8, size: 1, type: "Plain" },
    { x: 4, y: 9, size: 1, type: "Mid" },
    { x: 5, y: 6, size: 1, type: "Plain" },
    { x: 5, y: 7, size: 1, type: "Plain" },
    { x: 5, y: 8, size: 1, type: "Mid" },
    { x: 6, y: 6, size: 1, type: "Plain" },
    { x: 6, y: 7, size: 1, type: "Mid" },
    { x: 7, y: 6, size: 1, type: "Plain" },
    { x: 7, y: 7, size: 1, type: "Mid" },
    { x: 7, y: 29, size: 1, type: "Plain" },
    { x: 8, y: 5, size: 1, type: "Plain" },
    { x: 8, y: 6, size: 1, type: "Plain" },
    { x: 8, y: 7, size: 1, type: "Mid" },
    { x: 8, y: 29, size: 1, type: "Mid" },
    { x: 9, y: 5, size: 1, type: "Plain" },
    { x: 9, y: 6, size: 1, type: "Plain" },
    { x: 9, y: 7, size: 1, type: "Mid" },
    { x: 10, y: 5, size: 1, type: "Plain" },
    { x: 10, y: 6, size: 1, type: "Mid" },
    { x: 11, y: 5, size: 1, type: "Plain" },
    { x: 11, y: 6, size: 1, type: "Mid" },
    { x: 12, y: 6, size: 1, type: "Mid" },
    { x: 13, y: 5, size: 1, type: "Plain" },
    { x: 13, y: 6, size: 1, type: "Mid" },
    { x: 14, y: 5, size: 1, type: "Plain" },
    { x: 14, y: 6, size: 1, type: "Mid" },
    { x: 15, y: 5, size: 1, type: "Plain" },
    { x: 15, y: 6, size: 1, type: "Mid" },
    { x: 21, y: 7, size: 1, type: "Plain" },
    { x: 21, y: 8, size: 1, type: "Plain" },
    { x: 21, y: 9, size: 1, type: "Mid" },
    { x: 22, y: 7, size: 1, type: "Plain" },
    { x: 22, y: 8, size: 1, type: "Plain" },
    { x: 22, y: 9, size: 1, type: "Plain" },
    { x: 22, y: 10, size: 1, type: "Mid" },
    { x: 23, y: 7, size: 1, type: "Plain" },
    { x: 23, y: 8, size: 1, type: "Plain" },
    { x: 23, y: 9, size: 1, type: "Mid" },
    { x: 33, y: 9, size: 1, type: "Plain" },
    { x: 33, y: 10, size: 1, type: "Mid" },
    { x: 33, y: 11, size: 1, type: "Mid" },
    { x: 34, y: 9, size: 1, type: "Plain" },
    { x: 34, y: 10, size: 1, type: "Plain" },
    { x: 34, y: 11, size: 1, type: "Plain" },
    { x: 34, y: 12, size: 1, type: "Mid" },
    { x: 35, y: 11, size: 1, type: "Plain" },
    { x: 35, y: 12, size: 1, type: "Plain" },
    { x: 35, y: 13, size: 1, type: "Mid" },
    { x: 36, y: 9, size: 1, type: "Plain" },
    { x: 36, y: 12, size: 1, type: "Plain" },
    { x: 36, y: 13, size: 1, type: "Mid" },
    { x: 37, y: 9, size: 1, type: "Plain" },
    { x: 37, y: 10, size: 1, type: "Plain" },
    { x: 37, y: 11, size: 1, type: "Plain" },
    { x: 37, y: 12, size: 1, type: "Plain" },
    { x: 37, y: 13, size: 1, type: "Mid" },
    { x: 38, y: 9, size: 1, type: "Plain" },
    { x: 38, y: 10, size: 1, type: "Plain" },
    { x: 38, y: 11, size: 1, type: "Plain" },
    { x: 38, y: 12, size: 1, type: "Mid" },
    { x: 39, y: 9, size: 1, type: "Plain" },
    { x: 39, y: 11, size: 1, type: "Plain" },
    { x: 39, y: 12, size: 1, type: "Mid" },
    { x: 40, y: 9, size: 1, type: "Plain" },
    { x: 40, y: 10, size: 1, type: "Plain" },
    { x: 40, y: 11, size: 1, type: "Mid" },
    { x: 41, y: 9, size: 1, type: "Plain" },
    { x: 41, y: 10, size: 1, type: "Mid" },
    ],
    bricks: [
    { x: 0, y: 8, size: 1 },
    { x: 0, y: 9, size: 1 },
    { x: 1, y: 8, size: 1 },
    { x: 1, y: 9, size: 1 },
    { x: 2, y: 5, size: 1 },
    { x: 3, y: 5, size: 1 },
    { x: 3, y: 6, size: 1 },
    { x: 4, y: 5, size: 1 },
    { x: 4, y: 6, size: 1 },
    { x: 5, y: 5, size: 1 },
    { x: 6, y: 5, size: 1 },
    { x: 7, y: 5, size: 1 },
    { x: 9, y: 29, size: 1 },
    { x: 12, y: 5, size: 1 },
    { x: 35, y: 9, size: 1 },
    { x: 35, y: 10, size: 1 },
    { x: 36, y: 10, size: 1 },
    { x: 36, y: 11, size: 1 },
    { x: 39, y: 10, size: 1 },
    ],
    edges: [
    { x: 10, y: 29, type: "RightTop" },
    { x: 11, y: 29, type: "RightMid" },
    { x: 12, y: 29, type: "RightBot" },
    { x: 13, y: 29, type: "LeftTop" },
    { x: 14, y: 29, type: "LeftMid" },
    { x: 15, y: 29, type: "LeftBot" },
    { x: 16, y: 4, type: "RightTop" },
    { x: 16, y: 5, type: "RightMid" },
    { x: 16, y: 6, type: "RightBot" },
    { x: 20, y: 6, type: "LeftTop" },
    { x: 20, y: 7, type: "LeftMid" },
    { x: 20, y: 8, type: "LeftBot" },
    { x: 24, y: 6, type: "RightTop" },
    { x: 24, y: 7, type: "RightMid" },
    { x: 24, y: 8, type: "RightBot" },
    { x: 32, y: 8, type: "LeftTop" },
    { x: 32, y: 9, type: "LeftMid" },
    { x: 32, y: 10, type: "LeftBot" },
    { x: 42, y: 8, type: "RightTop" },
    { x: 42, y: 9, type: "RightMid" },
    { x: 42, y: 10, type: "RightBot" },
    ],
    platforms: [
    { x: 16, y: 29, size: 1, scale: 1, type: "Single", moving: false, direction: 1, speed: 50 },
    { x: 17, y: 29, size: 1, scale: 2, type: "Double", moving: false, direction: 0, speed: 0 },
    { x: 25, y: 6, size: 1, scale: 2, type: "Double", moving: false, direction: 0, speed: 0 },
    { x: 27, y: 6, size: 1, scale: 1, type: "Single", moving: false, direction: 1, speed: 50 },
    { x: 28, y: 8, size: 1, scale: 2, type: "Double", moving: false, direction: 0, speed: 0 },
    { x: 30, y: 8, size: 1, scale: 1, type: "Single", moving: false, direction: 1, speed: 50 },
    ],
    beams: [
    { x: 18, y: 29, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 7, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 8, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 9, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 10, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 11, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 12, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 13, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 14, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 15, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 16, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 17, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 18, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 19, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 20, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 21, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 22, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 23, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 24, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 25, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 26, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 27, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 28, size: 1, scale: 2, type: "Long" },
    { x: 26, y: 29, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 9, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 10, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 11, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 12, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 13, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 14, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 15, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 16, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 17, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 18, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 19, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 20, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 21, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 22, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 23, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 24, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 25, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 26, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 27, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 28, size: 1, scale: 2, type: "Long" },
    { x: 29, y: 29, size: 1, scale: 2, type: "Long" },
    ],
    trunks: [
    { x: 5, y: 0, size: 2 },
    { x: 5, y: 1, size: 2 },
    { x: 5, y: 2, size: 2 },
    { x: 5, y: 3, size: 2 },
    { x: 6, y: 0, size: 2 },
    { x: 6, y: 1, size: 2 },
    { x: 6, y: 2, size: 2 },
    { x: 6, y: 3, size: 2 },
    { x: 19, y: 29, size: 2 },
    { x: 22, y: 2, size: 2 },
    { x: 22, y: 3, size: 2 },
    { x: 22, y: 4, size: 2 },
    { x: 22, y: 5, size: 2 },
    ],
    branches: [
    { x: 20, y: 29, size: 2 },
    ],
    leaves: [
    { x: 21, y: 1, size: 4, color: "Purple"},
    { x: 21, y: 29, size: 4, color: "Purple"},
    { x: 22, y: 0, size: 4, color: "Purple"},
    { x: 22, y: 29, size: 4, color: "Orange"},
    { x: 23, y: 1, size: 4, color: "Purple"},
    { x: 23, y: 29, size: 4, color: "OrangeBrown"},
    ],
    frogs: [
    { x: 1, y: 29, scale: 3, color: "blue_blue" },
    { x: 2, y: 29, scale: 3, color: "green_brown" },
    { x: 3, y: 29, scale: 3, color: "purple_white" },
    { x: 10, y: 3, scale: 3, color: "purple_white" },
    ],
    cats: [
    { x: 4, y: 29, scale: 5, chosenOne: true },
    ],
    pills: [
    { x: 5, y: 29, scale: 4 },
    ],
    };